apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: gitops-app-rollout
  namespace: default
spec:
  replicas: 2
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 30s }
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
        - name: gitops-app
          image: gcr.io/micro-environs-442313-i6/gitops-app:latest
          ports:
            - containerPort: 5000